# Generated by Django 4.0.4 on 2022-11-08 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0025_product_alertment_date_product_manufacture_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tax',
            name='tax_type',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
