# Generated by Django 4.0.4 on 2022-11-08 17:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0027_itemgroup_alter_product_group'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_code', models.IntegerField()),
                ('category_name', models.CharField(max_length=50)),
                ('item_group_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.itemgroup')),
            ],
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.category'),
        ),
    ]
